#!/bin/bash

export BLDME_DIRNAME="$( cd "$( dirname "$0" )" && cygpath -a -m `pwd` )"
export SCONS_DIR=$BLDME_DIRNAME/ext/scons-2.2.0
export SCONS_LIB_DIR=$SCONS_DIR/engine

case $1 in
(cygwin|cygwin-debug)
perl -I cons ./cons/cons.pl $2 -- --toolset=gcc,cygwin,boost,stlport,clo,zlib,jpeg,libpng -v3 ;;
(cygwin-release)
perl -I cons ./cons/cons.pl $2 -- --toolset=gcc,cygwin,boost,stlport,clo,zlib,jpeg,libpng --build=Release -v3 ;;
(win-release)
/c/perl/bin/perl -I cons ./cons/cons.pl $2 -- --toolset=msvc70,cygwin,boost,stlport,clo,zlib,jpeg,libpng  --build=Release -v3 ;;
(doc)
/c/perl/bin/perl -I cons ./cons/cons.pl $2-- --toolset=doxygen -v3 && cd doc/docsys && ./docsys dgd && ./docsys doxy ;;
(clean)
/c/s/perl/bin/perl -I cons ./cons/cons.pl $2 -- clean ;;
(win|win-debug)
/c/perl/bin/perl -I cons ./cons/cons.pl $2 -- --toolset=msvc70,cygwin,boost,stlport,clo,zlib,jpeg,libpng --nostlport-debug -v3 $3 $4 $5 $6;;
(consming|consmingw)
/c/perl64/bin/perl -I cons ./cons/cons.pl $2 -- --toolset=mingw,cygwin,boost,qt4,dgd2 -v3 --cygwin-root-dir=c:/cygwin --mingw-root-dir=c:/personal/mingw --qt4-root-dir=c:/personal/qt-4.8.0-src/qt-everywhere-opensource-src-4.8.0 --boost-root-dir=c:/personal/boost-1.47 --dgd2-root=c:/personal/dgd $3 $4 $5 $6;;
(ming|mingw|*)
/c/python-2.7.3/python.exe $SCONS_DIR/script/scons --compiler=mingw mingwbin=d:/s/mingw/bin boostinc=d:/s/boost-1.47/include/boost-1_47 boostlib=d:/s/boost-1.47/lib boostlibsuf="-mgw45-mt-d-1_47" $2 $3 $4 $5 $6 $7 $8 $9;;
esac

# 
# Local Variables:
# compile-command: "bash -c \"./bldme mingw\""
# End:
#
