# -*- mode:python -*-
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# Copyright (c) Dimitry Kloper <kloper@users.sf.net> 2002-2012
# 
# This file is a part of the Scooter project. 
#
# dgd/SConscript -- construction file for dgd common dll
#

import os 
import sys
import string

Import('env', 'version')

env = env.Clone()

variant = env.subst('$VARIANT')
env.VariantDir(variant, 'src')

env.Append(CPPPATH = ['#blib/include', '$DGDINC'] )
env.Append(CPPDEFINES = {
    'DGD_DLL': None,
    'WINVER': '0x0502'
})

env.Append(CXXFLAGS = ['-mthreads', '-isystem', '$BOOSTINCDIR'])

env.Append(LIBPATH = ['#blib/lib', '$BOOSTLIBDIR'])
env.Append(LDFLAGS = ['-mthreads', '-mconsole'])

srclist = map( lambda fname: os.path.join(variant,fname), 
               [ 'dgd.cpp' ] )

boost_libs = map( lambda lib: lib + '$BOOST_LIB_SUFFIX',
                              [ 'boost_program_options',
                                'boost_filesystem',
                                'boost_system',
                                'boost_thread' ])

dgd_name = env.subst('${CRSHPREFIX}dgd')

dgd = env.SharedLibrary(
    target = os.path.join(variant, dgd_name), 
    source = srclist,
    LIBS = boost_libs
)

env.Install('#blib/bin', dgd[0])
env.Install('#blib/lib', dgd[1])

#
# SConscript -- end of file
#

