# -*- mode:python -*-
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This file is a part of the Scooter project (http://sctr.sf.net). 
#
# common/SConscript -- construction file for common stuff for scooter
#

import os 
import sys
import string

Import('env', 'version')


variant = env.subst('$VARIANT')
env.VariantDir(variant, 'src')

inclist =  map( lambda fname: os.path.join(variant,fname),
                [ 'bezier.h',
                  'calculus.h',
                  'calculus_dgd.h',
                  'calculus_impl.h',
                  'geometry.h',
                  'geometry_dgd.h',
                  'geometry_impl.h',
                  'iterators.h' ])

env.Install('#blib/include/scooter', inclist)

#
# SConscript -- end of file
#

